import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Privacy Policy - Pure Glint Clean",
  description: "Privacy Policy for Pure Glint Clean residential cleaning services in North Fort Worth Area.",
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-white">
      <Header />
      <main className="pt-40 pb-16">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
              Privacy Policy
            </h1>
            <p className="mt-4 text-lg text-gray-600">
              Effective date: September 1, 2025
            </p>
          </div>

          <div className="prose prose-lg max-w-none prose-gray text-gray-900 [&>*]:text-gray-900 [&_p]:text-gray-900 [&_li]:text-gray-900">
            <div className="bg-blue-50 p-6 rounded-lg mb-8">
              <p className="text-lg text-gray-900">
                Pure Glint Clean, LLC (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;) operates the{" "}
                <a href="https://pureglintclean.com" className="text-blue-600 hover:text-blue-800">
                  https://pureglintclean.com
                </a>{" "}
                website (hereinafter referred to as the &quot;Service&quot;).
              </p>
              <p className="mt-4 text-gray-900">
                This page informs you of our policies regarding the collection, use and
                disclosure of personal data when you use our Service and the choices you have associated
                with that data.
              </p>
              <p className="mt-4 text-gray-900">
                We use your data to provide and improve the Service. By using the Service, you
                agree to the collection and use of information in accordance with this policy.
                Unless otherwise defined in this Privacy Policy, the terms used in this Privacy
                Policy have the same meanings as in our Terms and Conditions.
              </p>
            </div>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Definitions</h2>
            
            <div className="space-y-6">
              <div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">Service</h3>
                <p className="text-gray-900">Service is the <a href="https://pureglintclean.com" className="text-blue-600 hover:text-blue-800">https://pureglintclean.com</a> website operated by Pure Glint Clean, LLC</p>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">Personal Data</h3>
                <p className="text-gray-900">Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">Usage Data</h3>
                <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">Cookies</h3>
                <p>Cookies are small files stored on your device (computer or mobile device).</p>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">Data Controller</h3>
                <p>Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information is, or is to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">Data Processors (or Service Providers)</h3>
                <p>Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
              </div>

              <div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">Data Subject (or User)</h3>
                <p>Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
              </div>
            </div>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Information Collection and Use</h2>
            <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

            <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Types of Data Collected</h3>
            
            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Personal Data</h4>
            <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&quot;Personal Data&quot;). Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Cookies and Usage Data</li>
            </ul>
            <p className="mt-4">We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any or all of these communications from us by following the unsubscribe link or the instructions provided in any email we send.</p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Usage Data</h4>
            <p>We may also collect information on how the Service is accessed and used (&quot;Usage Data&quot;). This Usage Data may include information such as your computer&apos;s IP address, browser type, browser version, the pages you visit, the time and date of your visit, time spent on pages, device identifiers, and other diagnostic data.</p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Location Data</h4>
            <p>We may use and store information about your location if you give us permission (&quot;Location Data&quot;). We use this data to provide features and improve our Service. You can enable or disable location services via your device settings.</p>

            <h4 className="text-lg font-semibold text-gray-900 mt-4 mb-2">Tracking & Cookies Data</h4>
            <p>We use cookies and similar tracking technologies to track activity on our Service and hold certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.</p>
            
            <p className="mt-2"><strong>Examples of Cookies We Use:</strong></p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Session Cookies – to operate our Service</li>
              <li>Preference Cookies – to remember your preferences</li>
              <li>Security Cookies – for security purposes</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Use of Data</h2>
            <p>Pure Glint Clean, LLC uses the collected data to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Provide and maintain our Service</li>
              <li>Notify you about changes to our Service</li>
              <li>Allow you to participate in interactive features</li>
              <li>Provide customer support</li>
              <li>Gather analysis to improve the Service</li>
              <li>Monitor usage</li>
              <li>Detect, prevent and address technical issues</li>
              <li>Provide marketing and promotional materials (unless opted out)</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Retention of Data</h2>
            <p>We will retain your Personal Data only as long as necessary to fulfill the purposes outlined here. We may retain Usage Data for internal analysis and to strengthen security and functionality.</p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Transfer of Data</h2>
            <p>Your information may be transferred to—and maintained on—computers outside your state or country where data laws may differ.</p>
            <p className="mt-2">If you are located outside the United States and provide information to us, please note we transfer the data to the United States and process it there.</p>
            <p className="mt-2">All the above categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.</p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Disclosure of Data</h2>
            
            <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Business Transactions</h3>
            <p>In the event of a merger, acquisition, or asset sale, your Personal Data may be transferred.</p>

            <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Law Enforcement</h3>
            <p>We may disclose your data if required by law or legal requests.</p>

            <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Legal Requirements</h3>
            <p>We may disclose your Personal Data to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Comply with legal obligations</li>
              <li>Protect our rights</li>
              <li>Prevent wrongdoing</li>
              <li>Protect the safety of users or the public</li>
              <li>Protect against legal liability</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Security of Data</h2>
            <p>We strive to use commercially acceptable means to protect your data but cannot guarantee absolute security.</p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Service Providers</h2>
            <p>We may employ third-party companies and individuals to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Facilitate our Service</li>
              <li>Provide Service on our behalf</li>
              <li>Perform Service-related services</li>
              <li>Analyze usage of our Service</li>
            </ul>
            <p className="mt-2">They are obligated not to disclose or use your data for other purposes.</p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Analytics</h2>
            <p>We may use third-party Service Providers such as Google Analytics. For more information, visit: <a href="https://policies.google.com/privacy" className="text-blue-600 hover:text-blue-800">Google Privacy & Terms</a></p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Payments</h2>
            <p>We use third-party services for payment processing.</p>
            <p className="mt-2"><strong>Stripe</strong> - Privacy Policy: <a href="https://stripe.com/us/privacy" className="text-blue-600 hover:text-blue-800">https://stripe.com/us/privacy</a></p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Children&apos;s Privacy</h2>
            <p>We do not knowingly collect data from children under 18. If we become aware of such data, we will remove it.</p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Changes to This Privacy Policy</h2>
            <p>We may update this Privacy Policy. We&apos;ll notify you by:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Posting updates to this page</li>
              <li>Email and/or prominent notice on our Service</li>
              <li>Updating the &quot;effective date&quot; above</li>
            </ul>
            <p className="mt-2">Please review this policy periodically.</p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Contact Us</h2>
            <div className="bg-gray-50 p-6 rounded-lg">
              <p>If you have any questions about this Privacy Policy, please contact us:</p>
              <div className="mt-4 space-y-2">
                <p><strong>By email:</strong> <a href="mailto:contact@pureglintclean.com" className="text-blue-600 hover:text-blue-800">contact@pureglintclean.com</a></p>
                <p><strong>By phone:</strong> <a href="tel:8174057858" className="text-blue-600 hover:text-blue-800">(817) 405-7858</a></p>
                <p><strong>By mail:</strong> 4364 Western Center Blvd PMB 2006, Fort Worth, TX 76137</p>
              </div>
            </div>
          </div>

          <div className="mt-12 text-center">
            <Link
              href="/"
              className="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 transition-colors"
            >
              Back to Home
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}